### ISSUE TITLE
Error In Init

### ISSUE THREAD

**Issue by paulxtiseo** [CleverStack/cleverstack-cli#53]
From a fresh install of cleverstack into an empty folder on a Mac:
```
$ clever init aex-cleverstack -f
Preparing for installation...
  ├── ⚠ Deleting the installation path for aex-cleverstack before we begin installing!
  └── Creating project installation path...
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...ies/Experimental/aex-cleverstack/backend.  ├── Installing NPM modules...
  └── Installing bundledDependencies...
✔  Backend installation has completed successfully!

Installing Frontend...
  ├── Installation path is /Users/nnn/Documents/Repositories/Experimental/aex-cleverstack/frontend...
  ├── Downloading and extracting angular-seed...
  ├── Installing NPM modules...
  ├── Installing bundled modules...
  ├── Installing bower components...
  ├── Installing bower components for cs_messenger...
  ├── Installing bower components for cs_modal...
Error: Command failed: bower                        ENOTEMPTY ENOTEMPTY, rmdir '/Users/nnn/Documents/Repositories/Experimental/aex-cleverstack/frontend/app/components/select2'

Stack trace:
Error: ENOTEMPTY, rmdir '/Users/nnn/Documents/Repositories/Experimental/aex-cleverstack/frontend/app/components/select2'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)n    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20                                     at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Darwin 14.1.0 x64

Status @ 81s |   Installation Progress: [▒▒▒▒▒▒----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 2s   ┊
```

**Comment by pilsy** [comment]
This usually happens because of two reasons,

1) Stale bower cache ~ run `bower cache clean` to fix this
2) Because of permissions, try running with sudo and -A argument

**Comment by MauritzKruger** [comment]
Also experiencing error with fresh CleverStack setup, getting following result:
`````
clever init cs-latest
Preparing for installation...
  └── Creating project installation path...
Installing Backend...
  ├── Installation path is /vagrant/cs-latest/backend...
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...
  └── Installing bundledDependencies...
✔  Backend installation has completed successfully!

Installing Frontend...
  ├── Installation path is /vagrant/cs-latest/frontend...
  ├── Downloading and extracting angular-seed...
  ├── Installing NPM modules...
  ├── Installing bundled modules...
  ├── Installing bower components...
  ├── Installing bower components for cs_messenger...
  ├── Installing bower components for cs_modal...
Error: Command failed: bower                        ENOTEMPTY ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/jquery/src'

Stack trace:
Error: ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/jquery/src'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.13.0-32-generic x64
`````
Did run `bower cache clean` to fix this, but still got the same issue. Also tried running the init command with `sudo` and `-A` (eg. `sudo clever init cs-latest -A` argument

**Comment by paulxtiseo** [comment]
@pilsy, like MauritzKruger, the cache clean did not help. Got the same error after performing both of those suggestions.

**Comment by pilsy** [comment]
@paulxtiseo, @MauritzKruger, i think this is resolved now - can you try the steps in https://github.com/CleverStack/clever-orm/issues/34 please ?

**Comment by MauritzKruger** [comment]
@pilsy , I still have issue with init, here my command and output:
`````
clever init cs-latest -f
Preparing for installation...
  ├── ⚠ Deleting the installation path for cs-latest before we begin installing!
  └── Creating project installation path...
Installing Backend...
  ├── Installation path is /vagrant/cs-latest/backend...
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...
  └── Installing bundledDependencies...
✔  Backend installation has completed successfully!

Installing Frontend...
  ├── Installation path is /vagrant/cs-latest/frontend...
  ├── Downloading and extracting angular-seed...
  ├── Installing NPM modules...
  ├── Installing bundled modules...
  ├── Installing bower components...
  ├── Installing bower components for cs_messenger...
  ├── Installing bower components for cs_modal...
Error: Command failed: bower                        ENOTEMPTY ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/select2'

Stack trace:
Error: ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/select2'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.13.0-32-generic x64
`````

**Comment by MauritzKruger** [comment]
Ran following commands and init worked:
`````
bower cache clean
npm cache clean
clever init cs-latest -f
`````

**Comment by paulxtiseo** [comment]
Ran (in a fresh folder):
```
npm install -g cleverstack-cli
bower cache clean
npm cache clean
clever init aex-cleverstack -f
```
Also tried the last command with `sudo`, just in case. My installation process freezes now. It stays stuck at some step shown below. Is there a more verbose output option that could help you better?

```
Preparing for installation...
  └── Creating project installation path...
Installing Backend...
  ├── Installation path is /Users/ptiseo/Documents/Repositories/Experimental/aex-cleverstack/backend...ep Time: 1s   ┊
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...rogress: [▒---------]  7 %   ┊   Installing: Backend   ┊   Step: DownStatus @ 36.283m |   Installation Progress: [▒▒--------]  21 %   ┊   Installing: Backend   ┊   Step: Installing NPM modules...   ┊   Step Time: 2s   ┊
```

**Comment by pilsy** [comment]
Thanks for trying that command again @paulxtiseo , there is a more verbose option, run the command with `-v` to get verbose output, you can use `clever -h` on any command as well, so `clever init -h` will show you the options, or if you look in the README.md you will see the options :)

Let me know how you go, -v looks like it's the only thing that will show helpful information in this case

**Comment by MauritzKruger** [comment]
Ran fresh setup, `clever -V` returning version as 1.1.6, init did not work:
`````
clever init cs-latest
Preparing for installation...
  └── Creating project installation path...
Installing Backend...
  ├── Installation path is /vagrant/cs-latest/backend...
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...
  └── Installing bundledDependencies...
✔  Backend installation has completed successfully!

Installing Frontend...
  ├── Installation path is /vagrant/cs-latest/frontend...
  ├── Downloading and extracting angular-seed...
  ├── Installing NPM modules...
  ├── Installing bundled modules...
  ├── Installing bower components...
  ├── Installing bower components for cs_messenger...
  ├── Installing bower components for cs_modal...
Error: Command failed: bower                        ENOTEMPTY ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/jquery/src/var'

Stack trace:
Error: ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/jquery/src/var'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.13.0-32-generic x64
`````

**Comment by paulxtiseo** [comment]
My problem remains unchanged. It stalls at the same `Installing NPM modules` step, at the same 7%/21% point. It would be nice if the verbose option actually displayed which module was being attempted; I'm guessing one of them is blocking on some question or error behind the scenes...

**Comment by pilsy** [comment]
@MauritzKruger can you run `clever init cs-latest -v`

**Comment by MauritzKruger** [comment]
@pilsy ran command as requested, here my output:
`````
$ clever init cs-latest -v
Preparing for installation...
-----------------------------
args             = []
--force          = undefined
project          = "cs-latest"
projectFolder    = "/vagrant/cs-latest"
singleSeed       = false
installFrontend  = true
installBackend   = true
-----------------------------
  ├── Creating project installation path...
  ├── Creating installation path /vagrant/cs-latest...
  └── Preparing seed installation list...
Installing Backend...
  ├── Installation path is /vagrant/cs-latest/backend...
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...
make: Entering directory `/vagrant/cs-latest/backend/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/vagrant/cs-latest/backend/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
deepmerge@0.2.7 node_modules/deepmerge

rimraf@2.2.8 node_modules/rimraf

ncp@0.5.1 node_modules/ncp

grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean

clever-controller@1.2.0 node_modules/clever-controller

async@0.9.0 node_modules/async

underscore@1.8.2 node_modules/underscore

i@0.3.2 node_modules/i

validator@3.30.0 node_modules/validator

clever-injector@1.0.2 node_modules/clever-injector
└── underscore@1.7.0

uberclass@1.0.1 node_modules/uberclassress: [▒▒--------]  21 %   ┊   Installing: Backend   ┊   Step: Installing NPM modules...   ┊   Step Time: 2.233m   ┊

debug@2.1.1 node_modules/debug
└── ms@0.6.2

method-override@2.3.1 node_modules/method-override
├── methods@1.1.1
├── vary@1.0.0
└── parseurl@1.3.0

response-time@2.3.0 node_modules/response-time
├── on-headers@1.0.0
└── depd@1.0.0

grunt-concurrent@0.5.0 node_modules/grunt-concurrent
├── pad-stdio@0.1.1 (lpad@0.2.1)
└── async@0.2.10

cors@2.5.3 node_modules/cors
└── vary@1.0.0

connect-timeout@1.5.0 node_modules/connect-timeout
├── ms@0.7.0
├── on-headers@1.0.0
└── http-errors@1.2.8 (statuses@1.2.1, inherits@2.0.1)

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

should@4.0.4 node_modules/should

ejs@2.2.4 node_modules/ejs

morgan@1.5.1 node_modules/morgan
├── basic-auth@1.0.0
├── on-finished@2.2.0 (ee-first@1.1.0)
└── depd@1.0.0

time-grunt@1.0.0 node_modules/time-grunt
├── date-time@1.0.0
├── figures@1.3.5
├── pretty-ms@1.0.1 (parse-ms@1.0.0, get-stdin@4.0.1)
├── text-table@0.2.0
└── hooker@0.2.3

jshint-stylish@1.0.1 node_modules/jshint-stylish
├── log-symbols@1.0.2
├── text-table@0.2.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.0, has-ansi@1.0.3, strip-ansi@2.0.1)
└── string-length@1.0.0 (strip-ansi@2.0.1)

bluebird@2.9.12 node_modules/bluebird

chai@1.9.2 node_modules/chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

grunt-mocha-test@0.11.0 node_modules/grunt-mocha-test
├── fs-extra@0.9.1 (jsonfile@1.1.1, mkdirp@0.5.0)
└── hooker@0.2.3

body-parser@1.12.0 node_modules/body-parser
├── content-type@1.0.1
├── raw-body@1.3.3
├── bytes@1.0.0
├── depd@1.0.0
├── qs@2.3.3
├── on-finished@2.2.0 (ee-first@1.1.0)
├── type-is@1.6.0 (media-typer@0.3.0, mime-types@2.0.9)
└── iconv-lite@0.4.7

supertest@0.13.0 node_modules/supertest
├── methods@1.0.0
└── superagent@0.18.0 (methods@0.0.1, extend@1.2.1, qs@0.6.6, debug@0.7.4, cookiejar@1.3.2, component-emitter@1.1.2, reduce-component@1.0.1, mime@1.2.5, readable-stream@1.0.27-1, form-data@0.1.2, formidable@1.0.14)

nconf@0.7.1 node_modules/nconf
├── ini@1.3.3
└── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)

express@4.11.2 node_modules/express
├── utils-merge@1.0.0
├── fresh@0.2.4
├── methods@1.1.1
├── cookie@0.1.2
├── escape-html@1.0.1
├── merge-descriptors@0.0.2
├── range-parser@1.0.2
├── cookie-signature@1.0.5
├── finalhandler@0.3.3
├── vary@1.0.0
├── media-typer@0.3.0
├── parseurl@1.3.0
├── serve-static@1.8.1
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── on-finished@2.2.0 (ee-first@1.1.0)
├── depd@1.0.0
├── qs@2.3.3
├── etag@1.5.1 (crc@3.2.1)
├── send@0.11.1 (destroy@1.0.3, ms@0.7.0, mime@1.2.11)
├── proxy-addr@1.0.6 (forwarded@0.1.0, ipaddr.js@0.1.8)
├── type-is@1.5.7 (mime-types@2.0.9)
└── accepts@1.2.4 (negotiator@0.5.1, mime-types@2.0.9)

mocha@1.20.1 node_modules/mocha
├── diff@1.0.7
├── growl@1.7.0
├── commander@2.0.0
├── mkdirp@0.3.5
├── glob@3.2.3 (graceful-fs@2.0.3, inherits@2.0.1, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

compression@1.4.1 node_modules/compression
├── bytes@1.0.0
├── on-headers@1.0.0
├── vary@1.0.0
├── compressible@2.0.2 (mime-db@1.7.0)
└── accepts@1.2.4 (negotiator@0.5.1, mime-types@2.0.9)

grunt-contrib-connect@0.3.0 node_modules/grunt-contrib-connect
└── connect@2.7.11 (fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.0.5, send@0.1.1, formidable@1.0.14)

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── lodash@2.4.1
└── gaze@0.5.1 (globule@0.1.0)

moment@2.9.0 node_modules/moment

sinon@1.10.3 node_modules/sinon
├── util@0.10.3 (inherits@2.0.1)
└── formatio@1.0.2 (samsam@1.1.2)

matchdep@0.3.0 node_modules/matchdep
├── stack-trace@0.0.7
├── resolve@0.5.1
├── globule@0.1.0 (minimatch@0.2.14, glob@3.1.21, lodash@1.0.1)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

grunt-jsonlint@1.0.4 node_modules/grunt-jsonlint
└── jsonlint@1.6.0 (nomnom@1.8.1, JSV@4.0.2)

sendgrid@1.5.0 node_modules/sendgrid
├── smtpapi@1.1.0
├── mime@1.3.4
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, form-data@0.2.0, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.6.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, combined-stream@0.0.7, http-signature@0.10.1, bl@0.9.4, mime-types@2.0.9, tough-cookie@0.12.1, hawk@2.3.1)
└── lodash@2.4.1

grunt-contrib-jshint@0.10.0 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, minimatch@1.0.0, cli@0.6.5, htmlparser2@3.8.2)

grunt-nodemon@0.2.1 node_modules/grunt-nodemon
└── nodemon@1.0.20 (minimatch@0.2.14, ps-tree@0.0.3, update-notifier@0.1.10)

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── nopt@1.0.10 (abbrev@1.0.5)
├── exit@0.1.2
├── hooker@0.2.3
├── lodash@0.9.2
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

grunt-exec@0.4.6 node_modules/grunt-exec

karma@0.12.31 node_modules/karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── colors@0.6.2
├── q@0.9.7
├── mime@1.2.11
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map@0.1.43 (amdefine@0.1.0)
├── chokidar@1.0.0-rc3 (async-each@0.1.6, is-binary-path@1.0.0, glob-parent@1.0.0, readdirp@1.3.0, anymatch@1.1.0)
├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── lodash@2.4.1
├── connect@2.26.6 (cookie@0.1.2, fresh@0.2.4, pause@0.0.1, cookie-signature@1.0.5, vhost@3.0.0, response-time@2.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, media-typer@0.3.0, bytes@1.0.0, parseurl@1.3.0, depd@0.4.5, cookie-parser@1.3.4, connect-timeout@1.3.0, finalhandler@0.2.0, qs@2.2.4, debug@2.0.0, method-override@2.2.0, morgan@1.3.2, serve-favicon@2.1.7, type-is@1.5.7, serve-static@1.6.5, body-parser@1.8.4, csurf@1.6.6, multiparty@3.3.2, express-session@1.8.2, errorhandler@1.2.4, compression@1.1.2, serve-index@1.2.1)
├── useragent@2.0.10 (lru-cache@2.2.4)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
  └── Installing bundledDependencies...
✔  Backend installation has completed successfully!----]  21 %   ┊   Installing: Backend   ┊   Step: Installing NPM modules...   ┊   Step Time: 2.233m   ┊

Installing Frontend...
  ├── Installation path is /vagrant/cs-latest/frontend...
  ├── Downloading and extracting angular-seed...
  ├── Installing NPM modules...
make: Entering directory `/vagrant/cs-latest/frontend/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/vagrant/cs-latest/frontend/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  ├── Installing bundled modules...
  ├── Installing bower components...ogress: [▒▒▒▒▒-----]  50 %   ┊   Installing: Frontend   ┊   Step: Installing NPM modules...   ┊   Step Time: 6.850m   ┊
  ├── Installing bower components for /vagrant/cs-latest/frontend...
bower angular#1.2.6                      not-cached git://github.com/angular/bower-angular.git#1.2.6mns.git#*
bower angular#1.2.6                         resolve git://github.com/angular/bower-angular.git#1.2.6p: Installing bower components...   ┊   Step Time: 17s   ┊ ┊
bower angular-resource#1.2.6             not-cached git://github.com/angular/bower-angular-resource.git#1.2.6
bower angular-resource#1.2.6                resolve git://github.com/angular/bower-angular-resource.git#1.2.6
bower angular-cookies#1.2.6              not-cached git://github.com/angular/bower-angular-cookies.git#1.2.6
bower angular-cookies#1.2.6                 resolve git://github.com/angular/bower-angular-cookies.git#1.2.6
bower angular-sanitize#1.2.6             not-cached git://github.com/angular/bower-angular-sanitize.git#1.2.6
bower angular-sanitize#1.2.6                resolve git://github.com/angular/bower-angular-sanitize.git#1.2.6
bower angular-route#1.2.6                not-cached git://github.com/angular/bower-angular-route.git#1.2.6
bower angular-route#1.2.6                   resolve git://github.com/angular/bower-angular-route.git#1.2.6
bower angular-ui-bootstrap#~0.10.0       not-cached git://github.com/angular-ui/bootstrap.git#~0.10.0
bower angular-ui-bootstrap#~0.10.0          resolve git://github.com/angular-ui/bootstrap.git#~0.10.0: Installing bower components...   ┊   Step Time: 18s   ┊
bower es5-shim#~2.1.0                    not-cached git://github.com/es-shims/es5-shim.git#~2.1.0
bower es5-shim#~2.1.0                       resolve git://github.com/es-shims/es5-shim.git#~2.1.0
bower angular-http-auth#1.2.1            not-cached git://github.com/witoldsz/angular-http-auth.git#1.2.1
bower angular-http-auth#1.2.1               resolve git://github.com/witoldsz/angular-http-auth.git#1.2.1
bower async#~0.2.5                       not-cached git://github.com/caolan/async.git#~0.2.5
bower async#~0.2.5                          resolve git://github.com/caolan/async.git#~0.2.5
bower bootstrap#~3.0.3                   not-cached git://github.com/twbs/bootstrap.git#~3.0.3
bower bootstrap#~3.0.3                      resolve git://github.com/twbs/bootstrap.git#~3.0.3
bower jquery#~1.10.2                     not-cached git://github.com/jquery/jquery.git#~1.10.2
bower jquery#~1.10.2                        resolve git://github.com/jquery/jquery.git#~1.10.2   Step: Installing bower components...   ┊   Step Time: 18s   ┊
bower json3#~3.2.4                       not-cached git://github.com/bestiejs/json3.git#~3.2.4
bower json3#~3.2.4                          resolve git://github.com/bestiejs/json3.git#~3.2.4
bower requirejs#~2.1.9                   not-cached git://github.com/jrburke/requirejs-bower.git#~2.1.9
bower requirejs#~2.1.9                      resolve git://github.com/jrburke/requirejs-bower.git#~2.1.9Installing bower components...   ┊   Step Time: 18s   ┊
bower underscore#~1.5.2                  not-cached git://github.com/jashkenas/underscore.git#~1.5.2
bower underscore#~1.5.2                     resolve git://github.com/jashkenas/underscore.git#~1.5.2
bower pace#~0.5.5                        not-cached git://github.com/HubSpot/pace.git#~0.5.5
bower pace#~0.5.5                           resolve git://github.com/HubSpot/pace.git#~0.5.5
bower ui-bootstrap#~0.11.0               not-cached git://github.com/angular-ui/bootstrap.git#~0.11.0
bower ui-bootstrap#~0.11.0                  resolve git://github.com/angular-ui/bootstrap.git#~0.11.0: Installing bower components...   ┊   Step Time: 19s   ┊
bower ng-table#~0.3.3                    not-cached git://github.com/esvit/ng-table.git#~0.3.3
bower ng-table#~0.3.3                       resolve git://github.com/esvit/ng-table.git#~0.3.3
bower fontawesome#~4.1.0                 not-cached git://github.com/FortAwesome/Font-Awesome.git#~4.1.0
bower fontawesome#~4.1.0                    resolve git://github.com/FortAwesome/Font-Awesome.git#~4.1.0
bower selectn#~0.9.6                     not-cached git://github.com/wilmoore/selectn.git#~0.9.6
bower selectn#~0.9.6                        resolve git://github.com/wilmoore/selectn.git#~0.9.6
bower angular-bootstrap#~0.11.0          not-cached git://github.com/angular-ui/bootstrap-bower.git#~0.11.0
bower angular-bootstrap#~0.11.0             resolve git://github.com/angular-ui/bootstrap-bower.git#~0.11.0
bower select2#~3.4.8                     not-cached git://github.com/ivaynberg/select2.git#~3.4.8
bower select2#~3.4.8                        resolve git://github.com/ivaynberg/select2.git#~3.4.8Step: Installing bower components...   ┊   Step Time: 19s   ┊
bower angular-ui-select2#~0.0.5          not-cached git://github.com/angular-ui/ui-select2.git#~0.0.5
bower angular-ui-select2#~0.0.5             resolve git://github.com/angular-ui/ui-select2.git#~0.0.5
bower angular-ui#~0.4.0                  not-cached git://github.com/angular-ui/angular-ui.git#~0.4.0
bower angular-ui#~0.4.0                     resolve git://github.com/angular-ui/angular-ui.git#~0.4.0
bower momentjs#~2.8.1                    not-cached git://github.com/moment/moment.git#~2.8.1
bower momentjs#~2.8.1                       resolve git://github.com/moment/moment.git#~2.8.1
bower inflection#~1.3.8                  not-cached git://github.com/dreamerslab/node.inflection.git#~1.3.8
bower inflection#~1.3.8                     resolve git://github.com/dreamerslab/node.inflection.git#~1.3.8
bower angular-mocks#1.2.6                not-cached git://github.com/angular/bower-angular-mocks.git#1.2.6
bower angular-mocks#1.2.6                   resolve git://github.com/angular/bower-angular-mocks.git#1.2.6talling bower components...   ┊   Step Time: 20s   ┊
bower jquery-minicolors#~2.1.6           not-cached git://github.com/claviska/jquery-minicolors.git#~2.1.6
bower jquery-minicolors#~2.1.6              resolve git://github.com/claviska/jquery-minicolors.git#~2.1.6
bower angular-scenario#1.2.6             not-cached git://github.com/angular/bower-angular-scenario.git#1.2.6
bower angular-scenario#1.2.6                resolve git://github.com/angular/bower-angular-scenario.git#1.2.6
bower sinon#~1.7.3                       not-cached git://github.com/cjohansen/Sinon.JS.git#~1.7.3
bower sinon#~1.7.3                          resolve git://github.com/cjohansen/Sinon.JS.git#~1.7.3
bower chai#~1.8.1                        not-cached git://github.com/chaijs/chai.git#~1.8.1
bower chai#~1.8.1                           resolve git://github.com/chaijs/chai.git#~1.8.1
bower ng-table-resizable-columns#*         checkout master
bower angular#1.2.6                        download https://github.com/angular/bower-angular/archive/v1.2.6.tar.gz
bower angular-cookies#1.2.6                download https://github.com/angular/bower-angular-cookies/archive/v1.2.6.tar.gz
bower angular-sanitize#1.2.6               download https://github.com/angular/bower-angular-sanitize/archive/v1.2.6.tar.gz
bower angular-route#1.2.6                  download https://github.com/angular/bower-angular-route/archive/v1.2.6.tar.gz.gz
bower angular-http-auth#1.2.1              download https://github.com/witoldsz/angular-http-auth/archive/v1.2.1.tar.gz
bower es5-shim#~2.1.0                      download https://github.com/es-shims/es5-shim/archive/v2.1.0.tar.gz
bower angular-ui-bootstrap#~0.10.0         download https://github.com/angular-ui/bootstrap/archive/0.10.0.tar.gz
bower ui-bootstrap#~0.11.0                 download https://github.com/angular-ui/bootstrap/archive/0.11.2.tar.gz bower components...   ┊   Step Time: 38s   ┊
bower async#~0.2.5                         download https://github.com/caolan/async/archive/0.2.10.tar.gz
bower angular-http-auth#1.2.1               extract archive.tar.gz┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 38s   ┊
bower angular-cookies#1.2.6                 extract archive.tar.gz
bower angular-http-auth#1.2.1          invalid-meta angular-http-auth is missing "ignore" entry in bower.json
bower angular-http-auth#1.2.1              resolved git://github.com/witoldsz/angular-http-auth.git#1.2.1stalling bower components...   ┊   Step Time: 38s   ┊
bower angular-cookies#1.2.6            invalid-meta angular-cookies is missing "ignore" entry in bower.json
bower angular-cookies#1.2.6                resolved git://github.com/angular/bower-angular-cookies.git#1.2.6lling bower components...   ┊   Step Time: 38s   ┊
bower angular-sanitize#1.2.6                extract archive.tar.gz
bower angular-route#1.2.6                   extract archive.tar.gz
bower angular-sanitize#1.2.6           invalid-meta angular-sanitize is missing "ignore" entry in bower.json
bower angular-sanitize#1.2.6               resolved git://github.com/angular/bower-angular-sanitize.git#1.2.6ling bower components...   ┊   Step Time: 39s   ┊
bower angular-route#1.2.6              invalid-meta angular-route is missing "ignore" entry in bower.json
bower angular-route#1.2.6                  resolved git://github.com/angular/bower-angular-route.git#1.2.6talling bower components...   ┊   Step Time: 39s   ┊
bower angular-resource#1.2.6           invalid-meta angular-resource is missing "ignore" entry in bower.json
bower angular-resource#1.2.6               resolved git://github.com/angular/bower-angular-resource.git#1.2.6ling bower components...   ┊   Step Time: 39s   ┊
bower es5-shim#~2.1.0                       extract archive.tar.gz
bower es5-shim#~2.1.0                  invalid-meta es5-shim is missing "main" entry in bower.json
bower es5-shim#~2.1.0                  invalid-meta es5-shim is missing "ignore" entry in bower.jsonp: Installing bower components...   ┊   Step Time: 41s   ┊
bower es5-shim#~2.1.0                      resolved git://github.com/es-shims/es5-shim.git#2.1.0
bower angular#1.2.6                         extract archive.tar.gz
bower angular#1.2.6                    invalid-meta angular is missing "ignore" entry in bower.json
bower angular#1.2.6                        resolved git://github.com/angular/bower-angular.git#1.2.6
bower json3#~3.2.4                         download https://github.com/bestiejs/json3/archive/v3.2.6.tar.gz
bower async#~0.2.5                          extract archive.tar.gz
bower async#~0.2.5                     invalid-meta async is missing "main" entry in bower.json
bower async#~0.2.5                     invalid-meta async is missing "ignore" entry in bower.jsonStep: Installing bower components...   ┊   Step Time: 42s   ┊
bower async#~0.2.5                         resolved git://github.com/caolan/async.git#0.2.10
bower jquery#~1.10.2                       download https://github.com/jquery/jquery/archive/1.10.2.tar.gz
bower requirejs#~2.1.9                     download https://github.com/jrburke/requirejs-bower/archive/2.1.16.tar.gz
bower bootstrap#~3.0.3                     download https://github.com/twbs/bootstrap/archive/v3.0.3.tar.gz
bower ui-bootstrap#~0.11.0                  extract archive.tar.gz
bower ui-bootstrap#~0.11.0             invalid-meta ui-bootstrap is missing "main" entry in bower.json5.2.tar.gz
bower ui-bootstrap#~0.11.0             invalid-meta ui-bootstrap is missing "ignore" entry in bower.jsonnstalling bower components...   ┊   Step Time: 46s   ┊
bower ui-bootstrap#~0.11.0                 resolved git://github.com/angular-ui/bootstrap.git#0.11.2
bower requirejs#~2.1.9                      extract archive.tar.gz
bower requirejs#~2.1.9                 invalid-meta requirejs is missing "ignore" entry in bower.json: Installing bower components...   ┊   Step Time: 48s   ┊
bower requirejs#~2.1.9                     resolved git://github.com/jrburke/requirejs-bower.git#2.1.16
bower angular-ui-bootstrap#~0.10.0          extract archive.tar.gz
bower ng-table#~0.3.3                      download https://github.com/esvit/ng-table/archive/v0.3.3.tar.gz
bower selectn#~0.9.6                       download https://github.com/wilmoore/selectn/archive/v0.9.6.tar.gz
bower angular-ui-bootstrap#~0.10.0     invalid-meta angular-ui-bootstrap is missing "main" entry in bower.json
bower angular-ui-bootstrap#~0.10.0     invalid-meta angular-ui-bootstrap is missing "ignore" entry in bower.jsong bower components...   ┊   Step Time: 50s   ┊
bower angular-ui-bootstrap#~0.10.0         resolved git://github.com/angular-ui/bootstrap.git#0.10.0
bower fontawesome#~4.1.0                   download https://github.com/FortAwesome/Font-Awesome/archive/v4.1.0.tar.gz
bower jquery#~1.10.2                        extract archive.tar.gz
bower angular-bootstrap#~0.11.0            download https://github.com/angular-ui/bootstrap-bower/archive/0.11.2.tar.gz
bower jquery#~1.10.2                   invalid-meta jquery is missing "ignore" entry in bower.json
bower jquery#~1.10.2                       resolved git://github.com/jquery/jquery.git#1.10.2┊   Step: Installing bower components...   ┊   Step Time: 52s   ┊
bower underscore#~1.5.2                     extract archive.tar.gz
bower underscore#~1.5.2                invalid-meta underscore is missing "main" entry in bower.json
bower underscore#~1.5.2                invalid-meta underscore is missing "ignore" entry in bower.json Installing bower components...   ┊   Step Time: 53s   ┊
bower underscore#~1.5.2                    resolved git://github.com/jashkenas/underscore.git#1.5.2
bower pace#~0.5.5                          download https://github.com/HubSpot/pace/archive/v0.5.7.tar.gz
bower json3#~3.2.4                         progress received 1.6MB
bower selectn#~0.9.6                        extract archive.tar.gz
bower selectn#~0.9.6                   invalid-meta selectn is missing "main" entry in bower.json
bower selectn#~0.9.6                   invalid-meta selectn is missing "ignore" entry in bower.jsonep: Installing bower components...   ┊   Step Time: 54s   ┊
bower selectn#~0.9.6                       resolved git://github.com/wilmoore/selectn.git#0.9.6
bower json3#~3.2.4                         progress received 2.0MB
bower json3#~3.2.4                         progress received 2.4MB
bower bootstrap#~3.0.3                     progress received 1.2MB
bower json3#~3.2.4                         progress received 2.8MB
bower bootstrap#~3.0.3                     progress received 1.3MB
bower ng-table#~0.3.3                       extract archive.tar.gz
bower json3#~3.2.4                         progress received 3.3MB
bower bootstrap#~3.0.3                     progress received 1.4MB
bower angular-ui-select2#~0.0.5            download https://github.com/angular-ui/ui-select2/archive/v0.0.5.tar.gz
bower bootstrap#~3.0.3                      extract archive.tar.gz
bower json3#~3.2.4                         progress received 3.7MB
bower angular-ui#~0.4.0                    download https://github.com/angular-ui/angular-ui/archive/v0.4.0.tar.gz
bower angular-bootstrap#~0.11.0             extract archive.tar.gz
bower select2#~3.4.8                       download https://github.com/ivaynberg/select2/archive/3.4.8.tar.gz
bower ng-table#~0.3.3                      mismatch Version declared in the json (0.3.2) is different than the resolved one (0.3.3)
bower ng-table#~0.3.3                      resolved git://github.com/esvit/ng-table.git#0.3.3┊   Step: Installing bower components...   ┊   Step Time: 59s   ┊
bower angular-bootstrap#~0.11.0        invalid-meta angular-bootstrap is missing "ignore" entry in bower.json
bower angular-bootstrap#~0.11.0            resolved git://github.com/angular-ui/bootstrap-bower.git#0.11.2
bower momentjs#~2.8.1                      download https://github.com/moment/moment/archive/2.8.4.tar.gz
bower json3#~3.2.4                         progress received 4.2MB┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 59s   ┊
bower inflection#~1.3.8                    download https://github.com/dreamerslab/node.inflection/archive/v1.3.8.tar.gz
bower json3#~3.2.4                         progress received 4.9MB
bower json3#~3.2.4                          extract archive.tar.gz
bower pace#~0.5.5                           extract archive.tar.gz
bower angular-ui-select2#~0.0.5             extract archive.tar.gz
bower angular-ui-select2#~0.0.5        invalid-meta angular-ui-select2 is missing "ignore" entry in bower.json
bower angular-ui-select2#~0.0.5            resolved git://github.com/angular-ui/ui-select2.git#0.0.5p: Installing bower components...   ┊   Step Time: 62s   ┊
bower bootstrap#~3.0.3                     resolved git://github.com/twbs/bootstrap.git#3.0.3
bower fontawesome#~4.1.0                   progress received 1.3MB
bower json3#~3.2.4                         resolved git://github.com/bestiejs/json3.git#3.2.6
bower fontawesome#~4.1.0                   progress received 1.8MB
bower inflection#~1.3.8                    resolved git://github.com/dreamerslab/node.inflection.git#1.3.8
bower fontawesome#~4.1.0                    extract archive.tar.gz
bower select2#~3.4.8                        extract archive.tar.gz
bower pace#~0.5.5                          resolved git://github.com/HubSpot/pace.git#0.5.7
bower select2#~3.4.8                   invalid-meta select2 is missing "ignore" entry in bower.json
bower select2#~3.4.8                       resolved git://github.com/ivaynberg/select2.git#3.4.8 Step: Installing bower components...   ┊   Step Time: 65s   ┊
bower chai#~1.8.1                          download https://github.com/chaijs/chai/archive/1.8.1.tar.gz3.tar.gz
bower angular-mocks#1.2.6                  download https://github.com/angular/bower-angular-mocks/archive/v1.2.6.tar.gz
bower angular-scenario#1.2.6               download https://github.com/angular/bower-angular-scenario/archive/v1.2.6.tar.gz
bower momentjs#~2.8.1                       extract archive.tar.gz┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 68s   ┊
bower angular-ui#~0.4.0                     extract archive.tar.gz
bower jquery-minicolors#~2.1.6             download https://github.com/claviska/jquery-minicolors/archive/2.1.10.tar.gz
bower angular-ui#~0.4.0                invalid-meta angular-ui is missing "main" entry in bower.json
bower angular-ui#~0.4.0                invalid-meta angular-ui is missing "ignore" entry in bower.json Installing bower components...   ┊   Step Time: 71s   ┊
bower angular-ui#~0.4.0                    resolved git://github.com/angular-ui/angular-ui.git#0.4.0
bower momentjs#~2.8.1                      resolved git://github.com/moment/moment.git#2.8.4
bower angular-mocks#1.2.6                   extract archive.tar.gz
bower chai#~1.8.1                           extract archive.tar.gz┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 72s   ┊
bower angular-mocks#1.2.6              invalid-meta angular-mocks is missing "ignore" entry in bower.json
bower angular-mocks#1.2.6                  resolved git://github.com/angular/bower-angular-mocks.git#1.2.6
bower chai#~1.8.1                          resolved git://github.com/chaijs/chai.git#1.8.1
bower sinon#~1.7.3                          extract archive.tar.gz
bower sinon#~1.7.3                     invalid-meta sinon is missing "main" entry in bower.json
bower sinon#~1.7.3                     invalid-meta sinon is missing "ignore" entry in bower.jsonStep: Installing bower components...   ┊   Step Time: 74s   ┊
bower sinon#~1.7.3                         resolved git://github.com/cjohansen/Sinon.JS.git#1.7.3
bower angular-scenario#1.2.6                extract archive.tar.gz
bower angular-scenario#1.2.6           invalid-meta angular-scenario is missing "ignore" entry in bower.json
bower angular-scenario#1.2.6               resolved git://github.com/angular/bower-angular-scenario.git#1.2.6ling bower components...   ┊   Step Time: 74s   ┊
bower jquery-minicolors#~2.1.6              extract archive.tar.gz
bower jquery-minicolors#~2.1.6             resolved git://github.com/claviska/jquery-minicolors.git#2.1.10
bower fontawesome#~4.1.0                   resolved git://github.com/FortAwesome/Font-Awesome.git#4.1.0
bower ng-table-resizable-columns#*         resolved https://github.com/esvit/ng-table-resizable-columns.git#61a9319533
bower angular-http-auth#1.2.1               install angular-http-auth#1.2.1
bower angular-cookies#1.2.6                 install angular-cookies#1.2.6talling: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 85s   ┊
bower angular-sanitize#1.2.6                install angular-sanitize#1.2.6
bower angular-route#1.2.6                   install angular-route#1.2.6
bower angular-resource#1.2.6                install angular-resource#1.2.6
bower es5-shim#~2.1.0                       install es5-shim#2.1.0
bower angular#1.2.6                         install angular#1.2.6
bower async#~0.2.5                          install async#0.2.10
bower ui-bootstrap#~0.11.0                  install ui-bootstrap#0.11.2
bower requirejs#~2.1.9                      install requirejs#2.1.16
bower angular-ui-bootstrap#~0.10.0          install angular-ui-bootstrap#0.10.0
bower jquery#~1.10.2                        install jquery#1.10.2
bower underscore#~1.5.2                     install underscore#1.5.2
bower selectn#~0.9.6                        install selectn#0.9.6
bower ng-table#~0.3.3                       install ng-table#0.3.3
bower angular-bootstrap#~0.11.0             install angular-bootstrap#0.11.2
bower angular-ui-select2#~0.0.5             install angular-ui-select2#0.0.5
bower bootstrap#~3.0.3                      install bootstrap#3.0.3
bower json3#~3.2.4                          install json3#3.2.6
bower inflection#~1.3.8                     install inflection#1.3.8
bower pace#~0.5.5                           install pace#0.5.7
bower select2#~3.4.8                        install select2#3.4.8
bower angular-ui#~0.4.0                     install angular-ui#0.4.0
bower momentjs#~2.8.1                       install momentjs#2.8.4
bower angular-mocks#1.2.6                   install angular-mocks#1.2.6
bower chai#~1.8.1                           install chai#1.8.1
bower sinon#~1.7.3                          install sinon#1.7.3
bower angular-scenario#1.2.6                install angular-scenario#1.2.6
bower jquery-minicolors#~2.1.6              install jquery-minicolors#2.1.10
bower fontawesome#~4.1.0                    install fontawesome#4.1.0
bower ng-table-resizable-columns#*          install ng-table-resizable-columns#61a9319533

angular-http-auth#1.2.1 app/components/angular-http-auth]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 96s   ┊
└── angular#1.2.6

angular-cookies#1.2.6 app/components/angular-cookies
└── angular#1.2.6

angular-sanitize#1.2.6 app/components/angular-sanitize
└── angular#1.2.6

angular-route#1.2.6 app/components/angular-route
└── angular#1.2.6

angular-resource#1.2.6 app/components/angular-resource
└── angular#1.2.6

es5-shim#2.1.0 app/components/es5-shim

angular#1.2.6 app/components/angular

async#0.2.10 app/components/async

ui-bootstrap#0.11.2 app/components/ui-bootstrap

requirejs#2.1.16 app/components/requirejs

angular-ui-bootstrap#0.10.0 app/components/angular-ui-bootstrap

jquery#1.10.2 app/components/jquery

underscore#1.5.2 app/components/underscore

selectn#0.9.6 app/components/selectn

ng-table#0.3.3 app/components/ng-table
└── angular#1.2.6

angular-bootstrap#0.11.2 app/components/angular-bootstrap
└── angular#1.2.6

angular-ui-select2#0.0.5 app/components/angular-ui-select2
├── angular#1.2.6
├── jquery#1.10.2
└── select2#3.4.8

bootstrap#3.0.3 app/components/bootstrap
└── jquery#1.10.2

json3#3.2.6 app/components/json3

inflection#1.3.8 app/components/inflection

pace#0.5.7 app/components/pace

select2#3.4.8 app/components/select2
└── jquery#1.10.2

angular-ui#0.4.0 app/components/angular-ui

momentjs#2.8.4 app/components/momentjs

angular-mocks#1.2.6 app/components/angular-mocks
└── angular#1.2.6

chai#1.8.1 app/components/chai

sinon#1.7.3 app/components/sinon

angular-scenario#1.2.6 app/components/angular-scenario
└── angular#1.2.6

jquery-minicolors#2.1.10 app/components/jquery-minicolors

fontawesome#4.1.0 app/components/fontawesome

ng-table-resizable-columns#61a9319533 app/components/ng-table-resizable-columns
└── angular#1.2.6
  ├── Installing bower components for cs_messenger...
  ├── Installing bower components for cs_modal...▒▒▒----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components...   ┊   Step Time: 96s   ┊
bower select2#~3.4              cached git://github.com/ivaynberg/select2.git#3.4.8
bower select2#~3.4            validate 3.4.8 against git://github.com/ivaynberg/select2.git#~3.4 Step: Installing bower components for cs_modal...   ┊   Step Time: 4s   ┊┊
bower jquery#>= 1.7.1           cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#>= 1.7.1         validate 1.10.2 against git://github.com/jquery/jquery.git#>= 1.7.1Step: Installing bower components for cs_modal...   ┊   Step Time: 4s   ┊
bower jquery#>=1.6.4            cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#>=1.6.4          validate 1.10.2 against git://github.com/jquery/jquery.git#>=1.6.4 Step: Installing bower components for cs_modal...   ┊   Step Time: 4s   ┊
bower jquery#>= 1.9.0           cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#>= 1.9.0         validate 1.10.2 against git://github.com/jquery/jquery.git#>= 1.9.0
bower select2#~3.4              cached git://github.com/ivaynberg/select2.git#3.4.8
bower select2#~3.4            validate 3.4.8 against git://github.com/ivaynberg/select2.git#~3.4
bower jquery#>= 1.7.1           cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#>= 1.7.1         validate 1.10.2 against git://github.com/jquery/jquery.git#>= 1.7.1Step: Installing bower components for cs_modal...   ┊   Step Time: 4s   ┊
bower jquery#>=1.6.4            cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#>=1.6.4          validate 1.10.2 against git://github.com/jquery/jquery.git#>=1.6.4 Step: Installing bower components for cs_modal...   ┊   Step Time: 4s   ┊
bower jquery#>= 1.9.0           cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#>= 1.9.0         validate 1.10.2 against git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.7.1              new version for git://github.com/jquery/jquery.git#>= 1.7.1
bower jquery#>= 1.7.1          resolve git://github.com/jquery/jquery.git#>= 1.7.1Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 20s   ┊
bower jquery#>=1.6.4               new version for git://github.com/jquery/jquery.git#>=1.6.4
bower jquery#>=1.6.4           resolve git://github.com/jquery/jquery.git#>=1.6.4
bower jquery#>= 1.9.0              new version for git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.9.0          resolve git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.7.1         download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower jquery#>=1.6.4          download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower jquery#>= 1.7.1              new version for git://github.com/jquery/jquery.git#>= 1.7.1
bower jquery#>= 1.7.1          resolve git://github.com/jquery/jquery.git#>= 1.7.1Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 21s   ┊
bower jquery#>=1.6.4               new version for git://github.com/jquery/jquery.git#>=1.6.4
bower jquery#>=1.6.4           resolve git://github.com/jquery/jquery.git#>=1.6.4
bower jquery#>= 1.9.0              new version for git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.9.0          resolve git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.7.1         download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower jquery#>=1.6.4          download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower jquery#>= 1.9.0         download https://github.com/jquery/jquery/archive/2.1.3.tar.gz ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 21s   ┊
bower jquery#>= 1.7.1          extract archive.tar.gz
bower jquery#>= 1.7.1          extract archive.tar.gz
bower jquery#>=1.6.4           extract archive.tar.gz
bower jquery#>= 1.7.1         resolved git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.7.1         resolved git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.9.0          extract archive.tar.gz
bower jquery#>=1.6.4          progress received 0.6MB
bower jquery#>=1.6.4          resolved git://github.com/jquery/jquery.git#2.1.3
bower jquery#>=1.6.4           extract archive.tar.gz
bower jquery#>= 1.9.0          extract archive.tar.gz
bower jquery#>= 1.9.0         resolved git://github.com/jquery/jquery.git#2.1.3
bower jquery#>=1.6.4          resolved git://github.com/jquery/jquery.git#2.1.3
bower select2#~3.4             install select2#3.4.8
bower jquery#>= 1.7.1          install jquery#2.1.3▒----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 43s   ┊
bower jquery#>= 1.9.0         resolved git://github.com/jquery/jquery.git#2.1.3
bower select2#~3.4             install select2#3.4.8----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 43s   ┊
bower jquery#>= 1.7.1          install jquery#2.1.3
bower                        ENOTEMPTY ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/select2'
 Status @ 12.283m |   Installation Progress: [▒▒▒▒▒▒----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 43s   ┊
Stack trace:
Error: ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/select2'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.13.0-32-generic x64
Error: Command failed: bower                        ENOTEMPTY ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/select2'
 Status @ 12.283m |   Installation Progress: [▒▒▒▒▒▒----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 43s   ┊
Stack trace:
Error: ENOTEMPTY, rmdir '/vagrant/cs-latest/frontend/app/components/select2'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.13.0-32-generic x64

Status @ 12.300m |   Installation Progress: [▒▒▒▒▒▒----]  64 %   ┊   Installing: Frontend   ┊   Step: Installing bower components for cs_modal...   ┊   Step Time: 43s   ┊
`````

**Comment by pilsy** [comment]
by any chance are you putting the files inside the vagrant shared directory like on oracle virtual box? there are known issues with that

**Comment by pilsy** [comment]
Any feedback @MauritzKruger ?

**Comment by paulxtiseo** [comment]
Updated to cleverstack-cli@1.1.6. Pretty much stays stuck at that point.

```
$ clever init aex-cleverstack -f -v
Preparing for installation...
-----------------------------
args             = []
--force          = true
project          = "aex-cleverstack"
projectFolder    = "/Users/ptiseo/Documents/Repositories/Experimental/aex-cleverstack"
singleSeed       = false
installFrontend  = true
installBackend   = true
-----------------------------
  ├── Creating project installation path...
  ├── Creating installation path /Users/ptiseo/Documents/Repositories/Experimental/aex-cleverstack...
  └── Preparing seed installation list...
Installing Backend...
  ├── Installation path is /Users/ptiseo/Documents/Repositories/Experimental/aex-cleverstack/backend...ep Time: 1s   ┊
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...rogress: [▒---------]  7 %   ┊   Installing: Backend   ┊   Step: Down
 Status @ 3s |   Installation Progress: [▒▒--------]  21 %   ┊   Installing: Backend   ┊   Step: Installing NPM modules...   ┊   Step Time: 2s   ┊
```

**Comment by pilsy** [comment]
@paulxtiseo , run `sudo rm -rf ~/.npm` and try again - it looks like a stale npm cache...

**Comment by marco-gallinari** [comment]
I experienced the same errors after upgrading npm to version 2.7.1.

After launching init twice in a row, I noticed that the exceptions were thrown on different packages, the second being thrown on a different package.

I then launched init -v -f a few more times, until the process completed succesfully.

**Comment by pilsy** [comment]
@marco-gallinari - it's weird that re-running it fixes the issue, it confirms that the issue has something to do with the cache - but i have been unable to replicate the issue locally.

Is this still an issue for anyone?

**Comment by paulxtiseo** [comment]
@pilsy still an issue for me. did the `rm` on my npm cache, (re)installed cleverstack-cli@1.2.2, and executed a`clever init aex-cleverstack -f -v`. Still stalls, this time earlier at "Preparing seed installation lis...". Wish I could say more, but not sure where to get any additional info.

**Comment by pilsy** [comment]
This should be resolved now, in https://github.com/CleverStack/cleverstack-cli/issues/65.

Please re-open the issue if it is not fixed for you
